### ISSUE TITLE
ODD to PDF conversions fail (maybe a Stylesheets issue?)

### ISSUE THREAD

**Issue by martindholmes** [TEIC/oxygen-tei#15]
Converting ODDs to PDF in Oxygen currently fails with the bleeding-edge plugin. Try:

TEI/P5/Test/testcorpus.odd

You get: "Effective boolean value is not defined for a sequence of two or more items starting with a boolean" in fo_figures.xsl line 336

Try:

TEI/P5/Test/relatedItem.odd

You get: "A sequence of more than one item is not allowed as the result of function tei:generateRefPrefix() ("relatedItem", "relatedItem")" in teiodds.xsl line 2382.

Could someone running the stable plugin and someone running with the default Oxygen framework in 18.1 please test and report back?

**Comment by lb42** [comment]
I think this has been broken for quite a while. Certainly I noticed it before upgrading to the new framework. Line 336 of fo_figures.xsl  reads
~~~~  
  <xsl:if test="not(ancestor::tei:table/tei:match(@rend,'tight'))">
~~~~
which I think should probably be
~~~~
 <xsl:if test="not(ancestor::tei:table[tei:match(@rend,'tight')])">
~~~~

**Comment by lb42** [comment]
... and yes, I can confirm both these errors are still there with oXygen 18.1 after having uninstalled the bleeding edge framework release (i.e. with no add ons).

**Comment by lb42** [comment]
I made the correction suggested above, and now it fails a bit further on, in a way that needs more knowledge of FOP than I have:

System ID: /home/lou/Public/TEI/P5/Exemplars/tei_bare.odd_xslt
Scenario: TEI ODD PDF
XML file: /home/lou/Public/TEI/P5/Exemplars/tei_bare.odd
XSL file: /home/lou/.com.oxygenxml/extensions/v18.1/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/odd2odd.xsl
Document type: TEI ODD
Engine name: Apache FOP
Severity: error
Description: The process 'Apache FOP' ended with code: 1.
The error was: 
FATAL - Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting
FATAL - Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting
ERROR - net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1616:-1)
ERROR - Exception
org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1616:-1)
net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1616:-1)
	at org.apache.fop.cli.InputHandlerFOP.transformTo(Unknown Source)
	at org.apache.fop.cli.InputHandlerFOP.renderTo(Unknown Source)
	at org.apache.fop.cli.Main.startFOP(Main.java:186)
	at org.apache.fop.cli.Main.main(Main.java:217)
Caused by: net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1616:-1)
	at net.sf.saxon.event.ContentHandlerProxy.handleSAXException(Unknown Source)
	at net.sf.saxon.event.ContentHandlerProxy.startContent(Unknown Source)
	at net.sf.saxon.event.NamespaceReducer.startContent(NamespaceReducer.java:215)
	at net.sf.saxon.event.ReceivingContentHandler.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.xinclude.XIncludeHandler.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:441)
	at net.sf.saxon.event.Sender.send(Sender.java:146)
	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:363)
	... 4 more
Caused by: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1616:-1)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:175)
	at com.sun.proxy.$Proxy2.missingLinkDestination(Unknown Source)
	at org.apache.fop.fo.flow.BasicLink.bind(BasicLink.java:95)
	at org.apache.fop.fo.FObj.processNode(FObj.java:126)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:291)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	... 21 more

---------

net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1616:-1)
	at net.sf.saxon.event.ContentHandlerProxy.handleSAXException(Unknown Source)
	at net.sf.saxon.event.ContentHandlerProxy.startContent(Unknown Source)
	at net.sf.saxon.event.NamespaceReducer.startContent(NamespaceReducer.java:215)
	at net.sf.saxon.event.ReceivingContentHandler.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.xinclude.XIncludeHandler.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:441)
	at net.sf.saxon.event.Sender.send(Sender.java:146)
	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:363)
	at org.apache.fop.cli.InputHandlerFOP.transformTo(Unknown Source)
	at org.apache.fop.cli.InputHandlerFOP.renderTo(Unknown Source)
	at org.apache.fop.cli.Main.startFOP(Main.java:186)
	at org.apache.fop.cli.Main.main(Main.java:217)
Caused by: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1616:-1)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:175)
	at com.sun.proxy.$Proxy2.missingLinkDestination(Unknown Source)
	at org.apache.fop.fo.flow.BasicLink.bind(BasicLink.java:95)
	at org.apache.fop.fo.FObj.processNode(FObj.java:126)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:291)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	... 21 more
---------
org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1616:-1)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:175)
	at com.sun.proxy.$Proxy2.missingLinkDestination(Unknown Source)
	at org.apache.fop.fo.flow.BasicLink.bind(BasicLink.java:95)
	at org.apache.fop.fo.FObj.processNode(FObj.java:126)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:291)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at net.sf.saxon.event.ContentHandlerProxy.startContent(Unknown Source)
	at net.sf.saxon.event.NamespaceReducer.startContent(NamespaceReducer.java:215)
	at net.sf.saxon.event.ReceivingContentHandler.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.xinclude.XIncludeHandler.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:441)
	at net.sf.saxon.event.Sender.send(Sender.java:146)
	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:363)
	at org.apache.fop.cli.InputHandlerFOP.transformTo(Unknown Source)
	at org.apache.fop.cli.InputHandlerFOP.renderTo(Unknown Source)
	at org.apache.fop.cli.Main.startFOP(Main.java:186)
	at org.apache.fop.cli.Main.main(Main.java:217)

Start location: 1616:0

**Comment by lb42** [comment]
BTW, converting an ordinary TEI document (e.g. Exemplars/simplePrint.tei) to PDF seems to work fine.

**Comment by martindholmes** [comment]
This needs some careful attention. I do know FO, so I can take a look at it. I would dearly love to be able to replace the current LaTeX-based build of the Guidelines with an FO version, so this might be a good start into the process.

**Comment by lb42** [comment]
Following Alex's observation on another ticket, I got rid of the "fo_figures.xsl" error by changing the line in question to read
~~~~
 <xsl:if test="not(ancestor::tei:table[1]/tei:match(@rend,'tight'))">
 ~~~~
 but PDF generation still fails. The problem is now in the FO generation, which fails when processing a &lt;dataRef> that uses @name rather than @key. With the latter, the FO code generated includes a pointer to the TEI datatype definition; with the former it cannot.

**Comment by lb42** [comment]
Cf. Stylesheet bug https://github.com/TEIC/Stylesheets/issues/203
